/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package desktopjava;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import org.jfree.chart.*; 
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author SafidyH
 */
public class Camembert extends javax.swing.JFrame {

    /**
     * Creates new form Camembert
     */
    Connections conn;
    Map<String,Integer> value;
    public Camembert(String annee) throws ClassNotFoundException {
        initComponents();
        conn=new Connections();
        value=new HashMap<>();
        String query = "SELECT statut, COUNT(*) AS nbr FROM (" +
                    "SELECT etudiant.`n°Inscription`, CASE " +
                    "WHEN SUM((notes.note*matiere.Coef))/(SUM(matiere.Coef)) < 7.5 THEN 'Exclu' " +
                    "WHEN SUM((notes.note*matiere.Coef))/(SUM(matiere.Coef)) < 10 THEN 'Redoublant' " +
                    "ELSE 'Admis' END AS statut " +
                    "FROM etudiant " +
                    "JOIN notes ON etudiant.`n°Inscription` = notes.`n°Inscription` " +
                    "JOIN matiere ON matiere.codemat = notes.codemat " +
                    "WHERE notes.Annee = '"+annee+"' " +
                    "GROUP BY etudiant.`n°Inscription`" +
                    ") AS subquery " +
                    "GROUP BY statut";
        try
        {
            Statement st=conn.start().createStatement();
            ResultSet res=st.executeQuery(query);
            while(res.next())
            {
                value.put(res.getString("statut"),res.getInt(2));
            }
            System.out.println(value.get("Admis")+" "+ value.get("Redoublant")+" "+value.get("Exclu"));
        }catch(SQLException e)
        {
            System.err.println(e.getMessage());
        }
        piechart();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     */
    public static void main(String args[]) throws ClassNotFoundException {
                //new Camembert("L1").setVisible(true);
    }
    
    private void piechart()
    {
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Admis",value.get("Admis"));
        pieDataset.setValue("Redoublant",value.get("Redoublant"));
        pieDataset.setValue("Exclus",value.get("Exclu"));
        JFreeChart pieChart = ChartFactory.createPieChart("Test camembert", pieDataset, true, true, true); 
        ChartPanel cPanel = new ChartPanel(pieChart);         
        System.out.println(value.get("Admis")+" "+ value.get("Redoublant")+" "+value.get("Exclu"));
        jPanel1.add(cPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
